# Generated by Django 4.0.4 on 2023-02-08 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university_app', '0005_alter_college_course_alter_staff_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='course',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='course',
        ),
        migrations.CreateModel(
            name='Staff_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university_app.course')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university_app.staff')),
            ],
        ),
        migrations.CreateModel(
            name='College_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university_app.college')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university_app.course')),
            ],
        ),
    ]
